/* ============================================================
   reports.js — PDF Generation
   NEU Library VMS v2
   ============================================================ */

import { getVisitsToday, getVisitsThisWeek,
         getVisitsThisMonth, getVisitsByRange, getAllVisits } from "./visits.js";

async function getReportData() {
  const period = document.getElementById("rpt-period").value;
  switch (period) {
    case "today":  return { visits: await getVisitsToday(),    label: "Today — "+fmtDate(new Date()) };
    case "week":   return { visits: await getVisitsThisWeek(),  label: "This Week" };
    case "month":  return { visits: await getVisitsThisMonth(), label: fmtMonth() };
    case "custom": {
      const f = document.getElementById("rpt-from").value;
      const t = document.getElementById("rpt-to").value;
      if (!f||!t) { alert("Please select both From and To dates."); return null; }
      return { visits: await getVisitsByRange(f,t), label: `${f} to ${t}` };
    }
    default: return { visits: await getAllVisits(), label: "All Time" };
  }
}

document.getElementById("btn-generate-pdf").addEventListener("click", async () => {
  const btn = document.getElementById("btn-generate-pdf");
  btn.disabled = true; btn.textContent = "Generating…";

  try {
    const result = await getReportData();
    if (!result) return;
    const { visits, label } = result;

    if (!visits.length) { alert("No visits found for the selected period."); return; }

    const type = document.querySelector(".report-option-card.selected")?.dataset.type || "summary";
    buildPDF(visits, label, type);
  } finally {
    btn.disabled = false;
    btn.innerHTML = "📄 &nbsp;Generate & Download PDF";
  }
});

function buildPDF(visits, periodLabel, type) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation:"portrait", unit:"mm", format:"a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 15;

  /* ── Header bar ── */
  doc.setFillColor(11,29,58);
  doc.rect(0,0,W,30,"F");
  doc.setFillColor(240,180,41);
  doc.rect(0,30,W,2.5,"F");

  doc.setFont("helvetica","bold");
  doc.setFontSize(13); doc.setTextColor(255,255,255);
  doc.text("NEW ERA UNIVERSITY LIBRARY", M, 12);
  doc.setFont("helvetica","normal");
  doc.setFontSize(8); doc.setTextColor(179,198,247);
  doc.text("Visitor Management System — Official Report", M, 19);
  doc.setFont("helvetica","bold");
  doc.setFontSize(7.5); doc.setTextColor(240,180,41);
  doc.text(new Date().toLocaleString("en-PH"), W-M, 12, { align:"right" });
  doc.setFont("helvetica","normal");
  doc.setTextColor(179,198,247);
  doc.text("Generated by Admin", W-M, 19, { align:"right" });

  /* ── Report heading ── */
  const titles = {
    summary:"Visitor Summary Report", detailed:"Detailed Visitor Log",
    college:"Breakdown by College",   purpose:"Breakdown by Purpose"
  };
  doc.setFont("helvetica","bold");
  doc.setFontSize(15); doc.setTextColor(11,29,58);
  doc.text(titles[type]||"Report", M, 44);
  doc.setFont("helvetica","normal");
  doc.setFontSize(8.5); doc.setTextColor(100,110,140);
  doc.text("Period: "+periodLabel, M, 51);

  /* ── Summary band ── */
  const colleges = new Set(visits.map(v=>v.college)).size;
  doc.setFillColor(232,239,254);
  doc.roundedRect(M, 56, W-2*M, 20, 3, 3, "F");
  doc.setDrawColor(179,198,247);
  doc.roundedRect(M, 56, W-2*M, 20, 3, 3, "S");

  [[String(visits.length),"Total Visits",M+12],
   [String(colleges),"Colleges",M+55],
  ].forEach(([val,lbl,x]) => {
    doc.setFont("helvetica","bold"); doc.setFontSize(16); doc.setTextColor(11,29,58);
    doc.text(val, x, 69);
    doc.setFont("helvetica","normal"); doc.setFontSize(7.5); doc.setTextColor(100,110,140);
    doc.text(lbl, x, 73);
  });

  let sy = 84;

  if (type === "summary") {
    const by = {};
    visits.forEach(v => {
      const ts = v.timestamp?.toDate ? v.timestamp.toDate() : new Date(v.createdAt);
      const k = ts.toLocaleDateString("en-PH",{year:"numeric",month:"short",day:"numeric"});
      by[k] = (by[k]||0)+1;
    });
    doc.autoTable({
      startY:sy, margin:{left:M,right:M},
      head:[["Date","Visitors"]],
      body:Object.entries(by).sort((a,b)=>new Date(b[0])-new Date(a[0]))
                              .map(([d,c])=>[d,String(c)]),
      headStyles:{ fillColor:[11,29,58], textColor:255, fontStyle:"bold", fontSize:8.5 },
      bodyStyles:{ fontSize:8 },
      alternateRowStyles:{ fillColor:[232,239,254] },
      columnStyles:{ 1:{ halign:"center" } }
    });
  }

  if (type === "detailed") {
    doc.autoTable({
      startY:sy, margin:{left:M,right:M},
      head:[["Date","Time","Name","Email","College","Purpose"]],
      body:visits.map(v=>{
        const ts = v.timestamp?.toDate ? v.timestamp.toDate() : new Date(v.createdAt);
        return [
          ts.toLocaleDateString("en-PH",{month:"short",day:"numeric",year:"numeric"}),
          ts.toLocaleTimeString("en-PH",{hour:"2-digit",minute:"2-digit"}),
          v.name, v.email,
          v.college.replace("College of ","Col. of ").substring(0,22),
          v.purpose
        ];
      }),
      headStyles:{ fillColor:[11,29,58], textColor:255, fontStyle:"bold", fontSize:7.5 },
      bodyStyles:{ fontSize:7 },
      alternateRowStyles:{ fillColor:[232,239,254] },
      columnStyles:{ 0:{cellWidth:22},1:{cellWidth:13},2:{cellWidth:30},
                     3:{cellWidth:38},4:{cellWidth:32} }
    });
  }

  if (type === "college") {
    const c = {};
    visits.forEach(v => { c[v.college]=(c[v.college]||0)+1; });
    doc.autoTable({
      startY:sy, margin:{left:M,right:M},
      head:[["College / Department","Visitors","% of Total"]],
      body:Object.entries(c).sort((a,b)=>b[1]-a[1])
                            .map(([k,v])=>[k,String(v),((v/visits.length)*100).toFixed(1)+"%"]),
      headStyles:{ fillColor:[11,29,58], textColor:255, fontStyle:"bold", fontSize:8.5 },
      bodyStyles:{ fontSize:8 },
      alternateRowStyles:{ fillColor:[232,239,254] },
      columnStyles:{ 1:{halign:"center"},2:{halign:"center"} }
    });
  }

  if (type === "purpose") {
    const c = {};
    visits.forEach(v => { c[v.purpose]=(c[v.purpose]||0)+1; });
    doc.autoTable({
      startY:sy, margin:{left:M,right:M},
      head:[["Purpose of Visit","Count","% of Total"]],
      body:Object.entries(c).sort((a,b)=>b[1]-a[1])
                            .map(([k,v])=>[k,String(v),((v/visits.length)*100).toFixed(1)+"%"]),
      headStyles:{ fillColor:[11,29,58], textColor:255, fontStyle:"bold", fontSize:8.5 },
      bodyStyles:{ fontSize:8 },
      alternateRowStyles:{ fillColor:[232,239,254] },
      columnStyles:{ 1:{halign:"center"},2:{halign:"center"} }
    });
  }

  /* ── Page footer ── */
  const pages = doc.internal.getNumberOfPages();
  for (let i=1;i<=pages;i++) {
    doc.setPage(i);
    doc.setFillColor(11,29,58);
    doc.rect(0,285,W,12,"F");
    doc.setFont("helvetica","normal"); doc.setFontSize(7); doc.setTextColor(179,198,247);
    doc.text("© 2025 New Era University Library · Visitor Management System", M, 292);
    doc.text(`Page ${i} of ${pages}`, W-M, 292, { align:"right" });
  }

  doc.save(`NEU-Library-${type}-${new Date().toISOString().split("T")[0]}.pdf`);
}

/* ── Helpers ── */
function fmtDate(d) {
  return d.toLocaleDateString("en-PH",{year:"numeric",month:"long",day:"numeric"});
}
function fmtMonth() {
  return new Date().toLocaleDateString("en-PH",{month:"long",year:"numeric"});
}
